= Demonstrating Rocket with Bash

This directory contains scripts and files which demonstrate a very
minimal Rocket container image. With it you can run a shell inside a
container and display the contents and environment.

The process also shows a way to place a binary in the container image
with the required shared libraries and extra tools to execute the
contaiiner tasks.

== Source Files

mktree.sh::
	A script to compose the image file tree
manifest::
	The rocket image description file
run.sh::
  The task script.  This file defines the set of operations that will
	be run inside the container

== Requirements

- actool
- rkt

== Image Structure

The image tree is composed under the current working directory in a
sub-directory named _image_.  It follows the AppContainer
specification for the location and format of the manifest file and the
location of the image contents.

    rootfs/
			/usr/bin/
				bash
				env
				ls
			/lib64/
			  lib*.so
			run.sh
			
== Building the File Tree

The _mktree.sh_ script will create the model tree for the image as
noted above.

    sh mktree.sh

The result is a directory named _image_ containing the image source
files.

== Building the Image

The image can be created merely using _tar_ but the AppContainer
project provides _actool_ to improve the process.  _actool_ will
validate the manifest before composing the image _.aci_ file.

    actool build image bash-f21-amd64.aci

If you are rebuilding the image add _--overwrite_ after the _build_
argument.

Not that the version in the manifest must be incremented for each
buid.  The _rkt_ binary examines the version number in the image
manifest, and if it finds that they are the same, it assumes that it
can use the cached copy of the image.

== Running the Image

This image is just an investigator.  It is used to demonstrate that
the Rocket container is running and to get a sense of the environment
in which container processes will run.

----------------------------------------------------------------------
sudo rkt run bash-f21-amd64.aci 
--- Running bash in Rocket ---
------------------------------

--- Environment ---

SHELL=/bin/sh
TERM=vt102
USER=root
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
HOME=/root
SHLVL=2
AC_APP_NAME=rocket-images.cloud.lab.eng.bos.redhat.com/bash
LOGNAME=root
_=/usr/bin/env

--- Root File System Contents ---

/:
lib64  run.sh  tmp  usr

/lib64:
ld-linux-x86-64.so.2  libc.so.6    liblzma.so.5     libselinux.so.1
libacl.so.1	      libcap.so.2  libpcre.so.1     libtinfo.so.5
libattr.so.1	      libdl.so.2   libpthread.so.0

/tmp:

/usr:
bin

/usr/bin:
bash  env  ls

--- Run complete ---
Sending SIGTERM to remaining processes...
Sending SIGKILL to remaining processes...
Unmounting file systems.
Unmounting /proc/sys/kernel/random/boot_id.
All filesystems unmounted.
Halting system.
----------------------------------------------------------------------

== References

- https://github.com/appc/spec/blob/master/SPEC.md#image-layout[AppContainer Image Layout]
- https://github.com/appc/spec/blob/master/SPEC.md#image-manifest-schema[AppContainer manifest schema]
- https://github.com/appc/spec#building-acis[Using _actool_]



